module.exports = {
    ADD_BLOCK: 'add-block',
    UPDATE_BLOCK: 'update-block',
    DELETE_BLOCK: 'delete-block',
    GET_BLOCK_BY_ID: 'get_block_by_id',
    ADD_ALBUM: 'add-album',
    UPDATE_ALBUM: 'update_album',
    DELETE_ALBUM: 'delete-album',
    GET_BLOCK_ALBUM_BY_ALBUM_ID: 'get-block-album-by-album-id',
    ADD_WORD: 'add-word',
    ADD_ALBUM_TO_BLOCK: 'add-album-to-block',
    GET_ALL_ALBUMS: 'get-all-albums',
    GET_ALL_LANGUAGES: 'get-all-languages',
    GET_ALL_BLOCKS: 'get-all-blocks',
    SETTINGS: 'settings',
    GET_SETTINGS: 'get-settings',
    SET_SETTINGS: 'set-settings',
    GET_BLOCK_IS_SHOW: 'get-block-is-show',
    SWITCH_VISIBILITY: 'switch-visibility'
}